### ISSUE TITLE
ISSUE PHP IS 8.0

### ISSUE THREAD

**Issue by FrankiePustorino** [rodber/chevereto-free#119]
Hi, 

I need to upgrade my hosting to PHP 8 and the current version of  Chevereto 1.5.1 on this repo doesn't support PHP 8.0 (Once I change hosting Cpanel to PHP 8.0  I see error 150  instead of any page of Chevereto)

If you need more details, I can provide some screen

**Comment by FrankiePustorino** [comment]
I can help in my free time, tell me when we can start

**Comment by FrankiePustorino** [comment]
How is progressing this point?

**Comment by rodber** [comment]
Hi @FrankiePustorino,

I don't have any hurry in supporting PHP 8 as 7.4 will get security updates until Nov 28 2022 meaning that it will be still on market until that. 

Don't worry, PHP 8 support should happen at sometime before that date 😉.

**Comment by FrankiePustorino** [comment]
Hi @rodber,

Currently I need to upgrade my hosting in order to support other platforms present in it, and they only software that held my update is chevereto.

Anyway, In case you will find the opportunity  to perform the corrective actions for support PHP 8.0, let me know.

Thanks for now for the answer

**Comment by rodber** [comment]
@FrankiePustorino

The fact that your hoster stop supporting 7.4 **before** the actual end of security updates shouldn't be encouraged by giving this company your business. Versioning involving major versions is not that trivial, at least not with a codebase this old and it adds extra unnecessary pressure to developers as the consumers of PHP versions are the software developers, not the end users of the software we create with that.

If php.net tells the world that php 7.4 code is supported until Nov 2022 that should be respected to the very last day.

**Comment by FrankiePustorino** [comment]
Hi @rodber  
I will consider your message, as anyway I'm in this sense of urgency due to my hosting requirements. 
I will try to explain to my hosting the effort need to have all platforms aligned to a major release as PHP 8.

Thanks and keep me informed when you start to work on this project

**Comment by FrankiePustorino** [comment]
Hi @rodber ,

Unfortunately my hosting removed from me the possibility to use PHP 7.4 anymore, they told that for security reason  they moving to PHP 8.0, therefore I cannot use anymore Chevereto free.

Let me know if you plan to upgrade the code to new version of PHP anytime soon.

Thanks
