### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by HoratioShaw** [rodber/chevereto-free#120]
When I upgraded to 1.5.1, my language changed back to English, and I couldn't find the switch language option in the settings.

**Comment by rodber** [comment]
Multi-domain language support has been removed in [1.5.0](https://github.com/rodber/chevereto-free/releases/tag/1.5.0)

**Comment by MyBlood** [comment]
> Multi-language support has been removed in [1.5.0](https://github.com/rodber/chevereto-free/releases/tag/1.5.0)

Greetings!

Why was it necessary to do that?
